# ============================================================
# Application Config
# ============================================================
server.port=${PORT:8080}
spring.application.name=${DD_SERVICE:spring-slo}

# ============================================================
# Actuator
# ============================================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ============================================================
# Logging
# ============================================================
logging.level.root=INFO
logging.pattern.console=%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
